# Version and library information
LIBRARY_NAME = "pywib"
LIBRARY_VERSION = "1.1.2"

# Event types for interaction tracking
class EventTypes:
    """ Event type constants for interaction tracking."""
    EVENT_ON_MOUSE_MOVE = 0
    """Event type for mouse move events."""
    EVENT_ON_CLICK = 1
    """Event type for mouse click events."""
    EVENT_ON_DOUBLE_CLICK = 2
    """Event type for mouse double click events."""
    EVENT_ON_MOUSE_DOWN = 3
    """Event type for mouse down events."""
    EVENT_ON_MOUSE_UP = 4
    """Event type for mouse up events."""
    EVENT_ON_WHEEL = 5
    """Event type for mouse wheel events, specificaly for wheel clicks."""
    EVENT_CONTEXT_MENU = 6
    """Event type for context menu events."""
    EVENT_ON_POINTER_MOVE = 7
    """Event type for touch move events, specific for mobile and tablet devices."""
    EVENT_POINTER_DOWN = 8
    """Event type for pointer down events."""
    EVENT_POINTER_UP = 9
    """Event type for pointer up events."""
    EVENT_POINTER_CANCEL = 10
    """Event type for pointer cancel events."""
    EVENT_WINDOW_SCROLL = 11
    """Event type for window scroll events."""
    EVENT_WINDOW_RESIZE = 12
    """Event type for window resize events."""
    EVENT_KEY_DOWN = 13
    """Event type for key down events."""
    EVENT_KEY_PRESS = 14
    """Event type for key press events."""
    EVENT_KEY_UP = 15
    """Event type for key up events."""
    EVENT_FOCUS = 16
    """Event type for focus events."""
    EVENT_BLUR = 17
    """Event type for blur events."""
    EVENT_ON_CHANGE_SELECTION_OBJECT = 18
    """Event type for change selection events."""
    EVENT_ON_CLICK_SELECTION_OBJECT = 19
    """Event type for click selection events."""
    EVENT_INIT_TRACKING = 100
    """Custom event type for initializing tracking."""
    EVENT_TRACKING_END = 200
    """Custom event type for ending tracking."""

class ComponentTypes:
    """ Component type constants for UI elements."""
    COMPONENT_TEXT_FIELD = 1
    COMPONENT_COMBOBOX = 2
    COMPONENT_OPTION = 3
    COMPONENT_RADIO_BUTTON = 4
    COMPONENT_CHECK_BOX = 5

class ColumnNames:
    """ Standard column names for DataFrame operations."""
    # Columns present on input DataFrame
    SESSION_ID = 'sessionId'
    SCENE_ID = 'sceneId'
    EVENT_TYPE = 'eventType'
    ELEMENT_ID = 'elementId'
    TIME_STAMP = 'timeStamp'
    X = 'x'
    Y = 'y'
    KEY_VALUE = 'keyValue'
    KEY_CODE = 'keyCode'
    SOURCE_SESSION_ID = 'sourceSessionId'
    # From here downwards we have the columns generated by methods
    DT = 'dt'
    DX = 'dx'
    DY = 'dy'
    DISTANCE = 'distance'
    VELOCITY= 'velocity'
    ACCELERATION = 'acceleration'
    JERKINESS = 'jerkiness'
    AUC_RATIO = 'auc_ratio'
    NUMBER_OF_PAUSES = 'num_pauses'
    MEAN_PAUSE_PER_TRACE = 'mean_pauses_per_trace'
    BACKSPACE_USAGE="backspace_usage"
    TOTAL_CHARS="total_characters"
    CLICK_SLIPS = 'click_slips'
    MAX_CLICK_SLIP = 'max_click_slip'
    MIN_CLICK_SLIP = 'min_click_slip'
    MEAN_CLICK_SLIP = 'mean_click_slip'
    MAX_CLICK_DURATION = 'max_click_duration'
    MIN_CLICK_DURATION = 'min_click_duration'
    MEAN_CLICK_DURATION = 'mean_click_duration'
    AUC_GEOM = 'auc_geometric'
    AUC_EXEC = 'auc_execution'
    AAD = 'aad'
    MAD_MAX = 'mad_mad'
    MIN_MAD = 'mean_mad'
    MEAN_MAD = 'min_mad'
    ANGLE = 'angle'
    ANGULAR_VELOCITY="angular_velocity"
    ANGULAR_ACCELERATION="angular_acceleration"

class KeyValues:
    """ 
    Key values for keyboard interactions. These values correspond to the 'key' property of KeyboardEvent objects in JavaScript.
    For more information read https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
    """
    KEY_VALUE_BACKSPACE = 'Backspace'
    """Key value for the Backspace key."""
    KEY_VALUE_DELETE = 'Delete'
    """Key value for the Delete key."""
    KEY_VALUE_DEAD = 'Dead'
    """Key value for dead keys, which are used to create accented characters."""
    KEY_UNIDENTIFIED = 'Unidentified'
    """Key value for unidentified keys, which are used when the key cannot be identified."""