# Version and library information
LIBRARY_NAME = "pywib"
LIBRARY_VERSION = "2.1.0"

# Event types for interaction tracking
class EventTypes:
    """ Event type constants for interaction tracking."""
    EVENT_ON_MOUSE_MOVE = 0
    """Event type for mouse move events."""
    EVENT_ON_CLICK = 1
    """Event type for mouse click events."""
    EVENT_ON_DOUBLE_CLICK = 2
    """Event type for mouse double click events."""
    EVENT_ON_MOUSE_DOWN = 3
    """Event type for mouse down events."""
    EVENT_ON_MOUSE_UP = 4
    """Event type for mouse up events."""
    EVENT_ON_WHEEL = 5
    """Event type for mouse wheel events, specificaly for wheel clicks."""
    EVENT_CONTEXT_MENU = 6
    """Event type for context menu events."""
    EVENT_ON_POINTER_MOVE = 7
    """Event type for touch move events, specific for mobile and tablet devices."""
    EVENT_POINTER_DOWN = 8
    """Event type for pointer down events."""
    EVENT_POINTER_UP = 9
    """Event type for pointer up events."""
    EVENT_POINTER_CANCEL = 10
    """Event type for pointer cancel events."""
    EVENT_WINDOW_SCROLL = 11
    """Event type for window scroll events."""
    EVENT_WINDOW_RESIZE = 12
    """Event type for window resize events."""
    EVENT_KEY_DOWN = 13
    """Event type for key down events."""
    EVENT_KEY_PRESS = 14
    """Event type for key press events."""
    EVENT_KEY_UP = 15
    """Event type for key up events."""
    EVENT_FOCUS = 16
    """Event type for focus events."""
    EVENT_BLUR = 17
    """Event type for blur events."""
    EVENT_ON_CHANGE_SELECTION_OBJECT = 18
    """Event type for change selection events."""
    EVENT_ON_CLICK_SELECTION_OBJECT = 19
    """Event type for click selection events."""
    EVENT_INIT_TRACKING = 100
    """Custom event type for initializing tracking."""
    EVENT_TRACKING_END = 200
    """Custom event type for ending tracking."""
    MOBILE_EVENTS_LIST = [EVENT_POINTER_CANCEL, EVENT_POINTER_DOWN, EVENT_POINTER_UP, EVENT_ON_POINTER_MOVE]
    """List of event types relevant for mobile interactions."""

class ComponentTypes:
    """ Component type constants for UI elements."""
    COMPONENT_TEXT_FIELD = 1
    """Component type for text field elements."""
    COMPONENT_COMBOBOX = 2
    """Component type for combobox elements."""
    COMPONENT_OPTION = 3
    """Component type for option elements."""
    COMPONENT_RADIO_BUTTON = 4
    """Component type for radio button elements."""
    COMPONENT_CHECK_BOX = 5
    """Component type for checkbox elements."""

class ColumnNames:
    """ Standard column names for DataFrame operations."""
    # Columns present on input DataFrame
    SESSION_ID = 'sessionId'
    """Column name for session or user identifier."""
    SCENE_ID = 'sceneId'
    """Column name for scene or secondary identifier."""
    EVENT_TYPE = 'eventType'
    """Column name for event type."""
    ELEMENT_ID = 'elementId'
    """Column name for element identifier."""
    TIME_STAMP = 'timeStamp'
    """Column name for timestamp of the event."""
    X = 'x'
    """Column name for x-coordinate of the event."""
    Y = 'y'
    """Column name for y-coordinate of the event."""
    KEY_VALUE = 'keyValue'
    """Column name for key value of keyboard events."""
    KEY_CODE = 'keyCode'
    """Column name for key code of keyboard events."""
    SOURCE_SESSION_ID = 'sourceSessionId'
    """Column name for source session identifier, used for merging DataFrames."""
    SCREEN_WIDTH ='screenWidth'
    SCREEN_HEIGHT='screenHeight'
    # From here downwards we have the columns generated by methods
    DT = 'dt'
    """Column name for delta time between events."""
    DX = 'dx'
    """Column name for delta x-coordinate between events."""
    DY = 'dy'
    """Column name for delta y-coordinate between events."""
    DISTANCE = 'distance'
    """Column name for distance between events."""
    VELOCITY= 'velocity'
    """Column name for velocity between events."""
    ACCELERATION = 'acceleration'
    """Column name for acceleration between events."""
    JERKINESS = 'jerkiness'
    """Column name for jerkiness between events."""
    AUC_RATIO = 'auc_ratio'
    """Column name for area under the curve ratio between events."""
    NUMBER_OF_PAUSES = 'num_pauses'
    """Column name for number of pauses in the interaction."""
    MEAN_PAUSE_PER_TRACE = 'mean_pauses_per_trace'
    """Column name for mean pauses per trace in the interaction."""
    BACKSPACE_USAGE="backspace_usage"
    """Column name for backspace usage in the interaction."""
    TOTAL_CHARS="total_characters"
    """Column name for total characters typed in the interaction."""
    CLICK_SLIPS = 'click_slips'
    """Column name for click slips in the interaction."""
    MAX_CLICK_SLIP = 'max_click_slip'
    """Column name for maximum click slip in the interaction."""
    MIN_CLICK_SLIP = 'min_click_slip'
    """Column name for minimum click slip in the interaction."""
    MEAN_CLICK_SLIP = 'mean_click_slip'
    """Column name for mean click slip in the interaction."""
    MAX_CLICK_DURATION = 'max_click_duration'
    """Column name for maximum click duration in the interaction."""
    MIN_CLICK_DURATION = 'min_click_duration'
    """Column name for minimum click duration in the interaction."""
    MEAN_CLICK_DURATION = 'mean_click_duration'
    """Column name for mean click duration in the interaction."""
    AUC_GEOM = 'auc_geometric'
    """Column name for geometric area under the curve in the interaction."""
    AUC_EXEC = 'auc_execution'
    """Column name for execution area under the curve in the interaction."""
    AAD = 'aad'
    """Column name for average absolute deviation in the interaction."""
    MAD_MAX = 'mad_mad'
    """Column name for maximum absolute deviation in the interaction."""
    MIN_MAD = 'min_mad'
    """Column name for minimum absolute deviation in the interaction."""
    MEAN_MAD = 'mean_mad'
    """Column name for mean absolute deviation in the interaction."""
    ANGLE = 'angle'
    """Column name for angle in the interaction."""
    ANGULAR_VELOCITY="angular_velocity"
    """Column name for angular velocity in the interaction."""
    ANGULAR_ACCELERATION="angular_acceleration"
    """Column name for angular acceleration in the interaction."""

class KeyValues:
    """ 
    Key values for keyboard interactions. These values correspond to the 'key' property of KeyboardEvent objects in JavaScript.
    For more information read https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
    """
    KEY_VALUE_BACKSPACE = 'Backspace'
    """Key value for the Backspace key."""
    KEY_VALUE_DELETE = 'Delete'
    """Key value for the Delete key."""
    KEY_VALUE_DEAD = 'Dead'
    """Key value for dead keys, which are used to create accented characters."""
    KEY_UNIDENTIFIED = 'Unidentified'
    """Key value for unidentified keys, which are used when the key cannot be identified."""